
#define AUDIO_CODEC_SUCCESS             0
#define ERROR_INPUT_RESOURCE_PATH		1
#define ERROR_OPEN_RESOURCE				2

#define ERROR_SPEEX_SAMPLETARE          100
#define ERROR_SPEEX_ENCODER_INIT        101
#define ERROR_SPEEX_NEW_ENCODER         102
#define ERROR_SPEEX_MALLOC_MEM          103



#define ERROR_AMR_INIT_CODECER			201
#define ERROR_AMR_OPEN_AMRFILE			202
#define ERROR_AMR_BAD_HEADER			203


//opus error code
#define ERROR_OPUS_SAMPLERATE			300
#define ERROR_OPUS_CHANNELS				301
#define ERROR_OPUS_CREATE_ENCODER		302

